### ISSUE TITLE
Upgrade from guzzle 3.6 to guzzle 6.0 to remove composer 'abandoned' notifications

### ISSUE THREAD

**Issue by LukeNZ** [ratchetphp/Ratchet#373] opened 2015-10-17 08:55 UTC
Since requiring in Ratchet to my project, every time I update composer dependencies or install new repositories, I am given a series of messages relating to Ratchet's use of Guzzle 3.6:

    Package guzzle/* is abandoned, you should avoid using it. Use guzzle/guzzle instead. 

This can be solved by upgrading Ratchet's dependency on Guzzle to Guzzle 6.

**Comment by cboden** [comment] 2015-10-26 13:40
Duplicate of #288, #297, #285, #305, #290, #287, #354.

This is fixed in the 0.4-wip branches and will be released with 0.4. This is not an error, it's a warning that those packages aren't receiving updates from their maintainer. They still parse HTTP just as well as before.

**Closed by cboden** 2015-10-26 13:40 UTC
Labels: duplicate
