### ISSUE TITLE
ratchet websocket is working on HTTP but on https it is not working.

### ISSUE THREAD

**Issue by NS000001** [ratchetphp/Ratchet#1018] opened 2023-06-08 09:45 UTC
on HTTP it was working but on HTTPS it is not working.
chat:352 WebSocket connection to 'wss://stage.example.com:8080/?token=XXXXXXXXX9a00' failed:

my nginx server block
```
location /chat/ {
proxy_pass http://websocket/;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
proxy_set_header Host $host;
proxy_read_timeout 300s;
proxy_send_timeout 300s;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}
```
WebSocketServer.php

```<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Ratchet\Server\IoServer;

use Ratchet\Http\HttpServer;

use Ratchet\WebSocket\WsServer;
use React\Socket\Server;
use React\Socket\SecureServer;

use React\EventLoop\Factory;
use App\Http\Controllers\SocketController;


class WebSocketServer extends Command
{
     /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'websocket:init';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
       $loop   = Factory::create();
    $webSock = new SecureServer(
        new Server('0.0.0.0:8080', $loop),
        $loop,

// i have used with and without certs still it doesn't work.
        array(
            'local_cert'        => '/etc/letsencrypt/live/stage.Domain.com/fullchain.pem', // path to your cert
            'local_pk'          => '/etc/letsencrypt/live/stage.Domain.com/privkey.pem', // path to your server private key
            'allow_self_signed' => TRUE, // Allow self signed certs (should be false in production)
            'verify_peer' => FALSE
        )
    );
    // Ratchet magic
    $webServer = new IoServer(
        new HttpServer(
            new WsServer(
                new SocketController()
            )
        ),
        $webSock
    );
    $loop->run();

         //$server = IoServer::factory(
             //new HttpServer(
                 //new WsServer(
               //      new SocketController()
             //    )
           //  ),
         //    8080
          
       //  );

     //    $server->run();
    }
}
```

chat.blade.php

```

var conn = new WebSocket('wss://stage.example.com:8080/?token={{ auth()->user()->userId}}');

var from_user_id = "{{ Auth::user()->userId }}";
// var user_type = "{{ Auth::user()->userId }}";

var to_user_id = "";

var user_id="";



conn.onopen = function(e){

        console.log("Connection ok!");

        load_unconnected_user(from_user_id);

        load_unread_notification(from_user_id);

        load_connected_chat_user(from_user_id);


};
```

used certbot certificate to implement HTTPS on domain stage.example.com in my nginx server block

can someone plz help to resolve this?
I have applied all of the above configurations but still facing the issue.

**Comment by SimonFrings** [comment] 2023-06-12 07:51
@NS000001 It seems like Ratchet is not the problem here, so there's no need for certificate handling in your code base. If your application runs behind a web server of your choice (here nginx), this server is responsible for handling encryption. All incoming request will first arrive at your nginx before being passed to your application in the background.

I can't see the full nginx configuration, so I'm unable to tell you what exactly is missing here, but this sounds like you need to configure your nginx for this, see http://nginx.org/en/docs/http/configuring_https_servers.html. Hope this helps :+1: 

I believe this should answer your question, so I will close this ticket for now. We can reopen this if you encounter the same issues again after trying out the solutions mentioned in here. If you do need to reopen the ticket, please provide some information about the steps you've taken so far, what worked and what didn't.

**Closed by SimonFrings** 2023-06-12 07:51 UTC
Labels: question

**Comment by NS000001** [comment] 2023-06-12 08:15
Hi Simon,

plz, have a look at my full Nginx configuration.

```
map $http_upgrade $connection_upgrade{
            default upgrade;
            `` close;
    }
    upstream websocket{
        server 127.0.0.1:8080; 
        #SERVER endpoint that handle ws:// connections
    }


server {
 
root /var/www/html/example/public;

index index.php index.html;
 
server_name stage.example.com;
 
error_log /home/ubuntu/error.log;
access_log /home/ubuntu/access.log;


location / {
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k;
try_files $uri $uri/ /index.php?$query_string;
}

location /chat/ {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
        proxy_pass_request_headers on;        
        proxy_buffers 8 32k;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto $scheme;        
        proxy_buffer_size 64k;    
        proxy_redirect         off;
}
 
location ~ \.php$ {
include snippets/fastcgi-php.conf;
fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
# With php-fpm (or other unix sockets);
}

location ~ /\.(?!well-known).* {
        deny all;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/stage.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/stage.example.com/privkey.pem; # managed by Certbot
    ssl_trusted_certificate /etc/letsencrypt/live/stage.example.com/chain.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = stage.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


listen 80 ;
listen [::]:80 ;
 
server_name stage.example.com;
    return 404; # managed by Certbot


}
```

let me know if here is sth wrong.

**Comment by SimonFrings** [comment] 2023-06-12 12:26
@NS000001 To be honest, I am not an expert when it comes to nginx configurations and there's a lot of stuff in here that could cause this behavior. I think setting up a system with a simple nginx configuration (focusing on the HTTPS part) might help in order to understand what a minimal configuration could look like. You can then compare both configuration files which makes it easier to work out the differences between them and find the cause of your problem. This shows at least if HTTPS is working in general.

We also worked with a lot of different hosting providers over the years, most of them were pretty convenient and had easy ways to enable HTTPS with the click of one button, might also solve your issue without having to deal with manually writing these configurations files.

Overall, I'm not sure how this is currently related to Ratchet, please understand that this is what we're trying to focus our support on here. If you can proof this problem only occurs when working with this project, please provide information about what steps you tried, what worked and what didn't, and we'll take a closer look.

**Comment by NS000001** [comment] 2023-06-12 13:26
I have changed the configuration to a minimum .

```
map $http_upgrade $connection_upgrade{
            default upgrade;
            `` close;
    }


server {
 
root /var/www/html/lexamplepublic;

index index.php index.html;
 
server_name stage.example.com;
 
error_log /home/ubuntu/error.log;
access_log /home/ubuntu/access.log;


location / {
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k;
try_files $uri $uri/ /index.php?$query_string;
}

location /chat/ {

        proxy_pass http://127.0.0.1:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s; 
      
}
 
location ~ \.php$ {
include snippets/fastcgi-php.conf;
fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
# With php-fpm (or other unix sockets);
}

location ~ /\.(?!well-known).* {
        deny all;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/stage.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/stage.example.com/privkey.pem; # managed by Certbot
    ssl_trusted_certificate /etc/letsencrypt/live/stage.example.com/chain.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = stage.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


listen 80 ;
listen [::]:80 ;
 
server_name stage.example.com;
    return 404; # managed by Certbot


}
```
and using ec2 instance from aws.
it should have works but still getting failed connection error.

![Screenshot from 2023-06-12 18-55-45](https://github.com/ratchetphp/Ratchet/assets/112945723/ed0e493a-a653-4776-b6e5-2634d501c814)

**Comment by NS000001** [comment] 2023-06-12 17:54
hi clue,

I m new to this error could u plz help to solve this error?
any suggestions would be helpful.

Thanks

**Comment by clue** [comment] 2023-06-13 09:55
@NS000001 I'm sure you understand this is not a general server support forum, so given this doesn't seem to be related to Ratchet, I suggest using your search engine of choice to look for more information elsewhere or check out my profile and let's get in touch if you're looking for professional support and want us to work out the details together.

Here are some pointers: It looks like you're trying to run Ratchet on `127.0.0.1:8090` and your nginx on `:80` (plaintext HTTP) and `443` (secure HTTPS). In this case, you would want to use nginx as a reverse proxy and only forward requests to Ratchet internally. As a result, you would never be able to access port `:8090` directly from outside at all and instead access it through your public ports. Make sure you can access it from the outside properly (such as when using curl) and once this is done, it should also work with Ratchet.

Happy to assist if you have any Ratchet-specific questions :+1:

**Comment by AforAshutosh** [comment] 2023-06-13 10:16
@clue 

Thanks for your support.
I have scheduled a 15 mint meet on the 15th from your GitHub, will see you then.

**Comment by NS000001** [comment] 2023-06-13 10:36
@clue 

Thanks for your quick response.
I have defined nginx as per ratchet documentation.
could u plz elaborate more
In this case, you would want to use nginx as a reverse proxy and only forward requests to Ratchet internally. As a result, you would never be able to access port :8090 directly from outside at all and instead access it through your public ports.

i already have 8090 port opened in security group and not using os firewall.
as i m facing this issue from last 2 weeks, that's why i have to sortout this asap.

**Comment by NS000001** [comment] 2023-06-19 10:36
@clue 

i have checked that websocket is working on http.
could you plz help me why it is not working on https.
![Screenshot from 2023-06-19 16-04-32](https://github.com/ratchetphp/Ratchet/assets/112945723/cce793fc-1ac6-48bf-be35-759d6820d549)

**Comment by SimonFrings** [comment] 2023-06-28 15:09
> after this i got error
>
> ![Screenshot from 2023-06-19 16-11-35](https://github.com/ratchetphp/Ratchet/assets/112945723/8ec91cb9-eb61-4e8e-970a-f493e36810d6)
>
> i have already shared all the details but plz let me know if anything missing here.

@NS000001 Does the error message end after saying `WebSocket connection to ... failed:` or is there additional content on why the connection failed?
