### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by Sleon4** [ratchetphp/Ratchet#1055] opened 2024-02-08 15:53 UTC
I am currently working on PHP 8.2.15 where there are warning outputs.

```log
Deprecated: Creation of dynamic property React\Socket\Connection::$decor is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php on line 83

Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$resourceId is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php on line 84

Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$remoteAddress is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php on line 87

Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$httpHeadersReceived is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php on line 33

Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$httpBuffer is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/Http/HttpRequestParser.php on line 30

Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$httpRequest is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php on line 112

Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$WebSocket is deprecated in /var/www/html/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php on line 114
```

![image](https://github.com/ratchetphp/Ratchet/assets/56183278/9ea86ff3-bf49-40d6-bdcb-12d4ed505379)

**Comment by clue** [comment] 2024-02-08 16:40
Closing as duplicate of #1003. Please take the time to review open tickets before posting any new tickets.

**Closed by clue** 2024-02-08 16:40 UTC
Labels: duplicate
