### ISSUE TITLE
Allowed memory size in Guzzle

### ISSUE THREAD

**Issue by bifidokk** [ratchetphp/Ratchet#308] opened 2015-04-21 09:44 UTC
Hello,
Daemon crash with fatal error after one day of work:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes) in /vendor/guzzle/guzzle/src/Guzzle/Http/Url.php on line 283

In this line:
```php
static $pathReplace = array(' ' => '%20', '?' => '%3F');
if (is_array($path)) {
   $path = '/' . implode('/', $path);
}

$this->path = strtr($path, $pathReplace);
```

Composer:
"require": {
        "cboden/ratchet": "0.3.*",
        "guzzle/guzzle": "~3.9",
		"predis/predis-async": "0.2.3"
    }

I think there is memory leak in code
How fix it?

p.s. Sorry for my bad english

**Comment by cboden** [comment] 2015-04-25 21:52
I think line 283 is a coincidence; the straw that broke the camels back. Your running application exceeded the soft memory limit of 128MB and halted. You can increase the memory a running script is allowed to utilize via a configuration option in your php.ini file.

Most importantly though, make sure you're cleaning up resources. After a connection closes if you do not dispose of any objects you're retaining regarding it your memory footprint will continue to grow.

**Comment by bifidokk** [comment] 2015-04-26 14:54
Hello, thanks for your answer. But the error is repeated every day. And it happen always at line 283

**Comment by bifidokk** [comment] 2015-04-27 10:13
So, it is memory leak actually. But I didn't understand what i do wrong.

For example? I write code:
http://pastie.org/10115967

And after few hours I have "Clients 1507" in log.
As if server doesn't know that some clients were disconnected.

**Comment by cboden** [comment] 2015-05-05 21:41
That could be a couple different things:

1) You have 1507 currently connected clients  ;-)
2) A LOT of sockets dropped without sending the TCP close frame
3) For some reason unset on the array isn't working (looks fine to my eyes though)

I'd suggest first trying to use `SplObjectStorage` like on the [intro tutorial] instead of an array to hold your open connections.

**Comment by bifidokk** [comment] 2015-05-06 07:50
It seems as "A LOT of sockets dropped without sending the TCP close frame".
How can I fix it? I use autobahn in frontend.  I suppose that some people just close the page with connecting client and it doesn't send closing command.

**Comment by cboden** [comment] 2015-05-06 13:14
Closing the page will properly terminal the connection. This type of error occurs if the network connection is dropped somewhere in the middle between the client and server. If 1500 dropped it could be your server's ISP had an outage (if that is indeed the cause).

**Closed** 2015-08-20 19:20 UTC
Labels: question
