### ISSUE TITLE
Use guzzle/guzzle?

### ISSUE THREAD

**Issue by leifnel** [ratchetphp/Ratchet#354] opened 2015-09-01 08:14 UTC
When installing Rachet for the first time, using php ~/composer.phar require cboden/ratchet, I got the messages:

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by cboden** [comment] 2015-09-01 13:04
Duplicate of #288, #297, #285, #305, #290, #287. 

This is fixed in the `0.4-wip` branches and will be released with 0.4. This is not an error, it's a warning that those packages aren't receiving updates from their maintainer. They still parse HTTP just as well as before.

**Closed by cboden** 2015-09-01 13:04 UTC
