### ISSUE TITLE
Fatal Error for handleData method in 0.4 Branch

### ISSUE THREAD

**Issue by haridarshan21** [ratchetphp/Ratchet#508] opened 2017-03-10 11:29 UTC
Hi
I'm using 0.4 dev branch with PHP 7.1. Till yesterday somehow it was working fine no fatal errors but today I tried voryx/thruway with ratchet 0.4 dev branch but didn't worked out so reverted back to only 0.4 dev branch. But all of sudden everything starts getting broke. 

Currently with 0.4 branch with PHP 7 gives me below mentioned Fatal Error but on using  0.3+ branch its works fine... Need to use 0.4 because of guzzle but not working. Kindly  help me out as its urgent

Here is the server script

```php
$server = IoServer::factory(
	new HttpServer(
		new WsServer(
			new DataManager()
		)
	),
	WEBSOCKET_PORT
);

$server->run();
```
Fatal Error which I'm getting with 0.4 branch

```php
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ratchet\Server\IoServer::handleData(), 1 passed and exactly 2 expected in /var/www/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php:113
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ratchet\Server\IoServer::handleData(), 1 passed and exactly 2 expected in /var/www/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php:113
Stack trace:
#0 [internal function]: Ratchet\Server\IoServer->handleData('GET / HTTP/1.1\r...')
#1 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#2 /var/www/vendor/react/stream/src/Stream.php(170): Evenement\EventEmitter->emit('data', Array)
#3 [internal function]: React\Stream\Stream->handleData(Resource id #47, Object(React\EventLoop\StreamSelectLoop))
#4 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #47, Object(React\EventLoop\StreamSelectLoop))
#5 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#6 /var/www/ut in /var/www/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php on line 113

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Ratchet\Server\IoServer::handleData(), 1 passed and exactly 2 expected in /var/www/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php:113
Stack trace:
#0 [internal function]: Ratchet\Server\IoServer->handleData('GET / HTTP/1.1\r...')
#1 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#2 /var/www/vendor/react/stream/src/Stream.php(170): Evenement\EventEmitter->emit('data', Array)
#3 [internal function]: React\Stream\Stream->handleData(Resource id #47, Object(React\EventLoop\StreamSelectLoop))
#4 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #47, Object(React\EventLoop\StreamSelectLoop))
#5 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#6 /var/www/ut in /var/www/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php on line 113
```

**Comment by cboden** [comment] 2017-03-10 14:23
This was caused by a BC in [ReactPHP/socket v0.5](https://github.com/reactphp/stream/releases/tag/v0.5.0) and should be fixed with the latest update to the branch.

**Comment by haridarshan21** [comment] 2017-03-10 14:28
@cboden  Thanks. 

Also which serializer can be used to serialize the Ratchet\WebSocket\Version\RFC6455\Connection object so that I can store it in redis for availability across multiple backend servers having WsServer running??

**Comment by cboden** [comment] 2017-03-10 14:32
That class has been removed in 0.4. You can't serialize it as it holds a resource (stream connection).

**Closed** 2017-03-27 14:52 UTC
