### ISSUE TITLE
Support symfony/http-foundation ^v7

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [ratchetphp/Ratchet#1067] opened 2024-07-06 13:00 UTC
I'm trying to install Ratchet on Laravel 11. According to the Laravel dependency graph `symfony/http-foundation@^7.0` is required and fixed.
So, if we can support `v7`, we can install Ratchet on Laravel 11.

**Comment by clue** [comment] 2024-07-06 13:47
Closing as duplicate of #1045. Please take the time to review open tickets before posting any new tickets and consider supporting this project by becoming a sponsor (#1054) ❤️

**Closed by clue** 2024-07-06 13:47 UTC
Labels: duplicate

**Comment by ebootingdev** [comment] 2024-12-13 03:37
Please i need the version for Symfony 7 D:
