### ISSUE TITLE
Socket in CLOSE_WAIT after it reaches 1024 connections

### ISSUE THREAD

**Issue by AntonioDilorenzo** [ratchetphp/Ratchet#713] opened 2019-02-04 10:29 UTC
hi, I'm using the socket for a web app, now that the connections are increasing, more and more often the socket hangs when the 1024 connections are reached. all the others are in the state of close_wait, I've already tried unlimit, but nothing has changed. Do you know if there is a parameter to change?
thanks so much for the help!

**Comment by mbonneau** [comment] 2019-02-11 14:25
This is caused by the remote side closing the connection and the local side not closing the connection. There may be something in your application code that could be changed to ensure that you are closing the connections once the remote hangs up on you.

**Closed** 2019-03-15 14:40 UTC
Labels: question
